version: '{build}'
image: Ubuntu2004
environment:
  global:
    HAXELIB_ROOT: /home/appveyor/haxelib

install:
  - cd /home/appveyor
  # Download Haxe and Neko from the PPA.
  - sudo add-apt-repository ppa:haxe/releases -y
  - sudo apt update
  - sudo apt install haxe neko tar gcc-7 g++-7 gcc-7-multilib g++-7-multilib -y
  - mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
  - haxelib install lime
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install flixel-tools
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install actuate
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
  - haxelib remove linc_luajit 
  - haxelib git linc_luajit https://github.com/EnigmaEngine/linc_luajit.git
  - haxelib remove polymod
  - haxelib git polymod https://github.com/MasterEric/polymod.git
  # Setup and build WebM.
  - haxelib git extension-webm https://github.com/KadeDev/extension-webm
  - haxelib run lime rebuild extension-webm windows
  - haxelib list
  - cd /home/appveyor/projects/enigma-engine-linux

build_script:
  - haxelib run lime build linux

after_build:
  - tar -cvf EnigmaEngine-Linux.tar -C /home/appveyor/projects/enigma-engine-linux/export/release/linux/bin .

artifacts:
- path: EnigmaEngine-Linux.tar
  name: Enigma Engine for Linux
