name: I found a bug!
description: Report incorrect behavior with Enigma Engine
title: 'Bug Report: '
labels: ["bug", "priority/triage"]
body:
- type: checkboxes
  id: checks
  attributes:
    label: Checks
    options:
      - label: >
          I have checked that this issue has not already been reported.
        required: true
      - label: >
          I have confirmed I am using the latest version of Enigma Engine.
        required: true
      - label: >
          I have validated that this issue is with the game and not a problem caused by a mod.
        required: true
- type: textarea
  id: problem
  attributes:
    label: Description
    description: Give a clear and concise summary of the bug. Describe the expected behavior and the actual behavior.
  validations:
    required: true
- type: textarea
  id: reproduction
  attributes:
    label: Steps to Reproduce
    description: Provide a simple set of steps that reliably produces the unexpected behavior.
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Logs
    description: Paste the contents of the log file (available in the 'logs' folder).
