blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions Page
    url: https://github.com/EnigmaEngine/EnigmaEngine/discussions
    about: Ask questions and get modding help here.
  - name: Documentation
    url: https://enigmaengine.github.io/
    about: View the official website for documentation and guides.
  - name: Documentation Issues
    url: https://github.com/EnigmaEngine/EnigmaEngine.github.io/issues
    about: Report issues with the documentation.