# This is a basic workflow to help you get started with Actions

name: Linux Build CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3
      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib haxe -y
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-ui
          haxelib install flixel-tools

          haxelib install haxe-strings
          haxelib install firetongue
          haxelib install munit
          haxelib install hamcrest

          haxelib git hscript https://github.com/HaxeFoundation/hscript
          haxelib git actuate https://github.com/jgranick/actuate
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit

          haxelib git polymod https://github.com/MasterEric/polymod
          haxelib git https://github.com/MasterEric/TJSON
          haxelib git linc_luajit https://github.com/EnigmaEngine/linc_luajit
          haxelib git mockatoo https://github.com/EnigmaEngine/mockatoo

          haxelib git extension-webm https://github.com/EnigmaEngine/extension-webm
          haxelib run lime rebuild extension-webm linux
          haxelib list
          haxelib run lime build linux
          
      - uses: actions/upload-artifact@v2
        with:
          name: Linux Build
          path: export/release/linux/bin
